// `cue cmd` scripts for the registry. Run from the repo root:
//
//     cue vet -c schema.cue dars.cue    dars.cue's own shape
//     cue cmd check                                map vs territory
//     cue cmd generate                             rewrite README.md's table
//
// tool/http fetches the Releases API, tool/file splices README.md, tool/exec
// shells out for unzip/shasum. No other runtime is involved.
//
// `[ if cond {a}, b ][0]` is CUE's switch idiom — see README, "Working on this
// repo", including the no-short-circuiting trap it carries.
package dars

import (
	"list"
	"strings"
	"strconv"
	"encoding/json"
	"tool/cli"
	"tool/http"
	"tool/file"
	"tool/exec"
	"tool/os"
	"regexp"
)

_repo: "C7-Digital/public-dars"
_api:  "https://api.github.com/repos/\(_repo)/releases?per_page=100"

_begin: "<!-- BEGIN GENERATED — edit dars.cue, not this block -->"
_end:   "<!-- END GENERATED -->"

// ── Turning the API's release list into per-stream versions ─────────────────

// The tag IS the index: nothing else records which stream a release belongs to.
#Parsed: {
	raw: [...]
	out: [ for r in raw if !r.draft && strings.Contains(r.tag_name, "/v") {
		let parts = strings.SplitN(r.tag_name, "/v", 2)
		{stream: parts[0], version: parts[1], tag: r.tag_name}
	}]
}

// `0.10.0` must sort above `0.9.0`, so compare numerically. Three components,
// each assumed < 1000; `check` reports any tag that does not parse.
#VNum: {
	v:  string
	_p: strings.Split(v, ".")
	ok: len(_p) == 3
	out: [ if ok {strconv.Atoi(_p[0])*1000000 + strconv.Atoi(_p[1])*1000 + strconv.Atoi(_p[2])}, 0][0]
}

#ByStream: {
	parsed: [...]
	out: {
		for sid, _ in streams {
			(sid): list.Sort(
				[ for p in parsed if p.stream == sid {p.version}],
				{x: string, y: string, less: (#VNum & {v: x}).out > (#VNum & {v: y}).out})
		}
	}
}

// ── Rendering ───────────────────────────────────────────────────────────────

#Row: {
	sid: string, s: #Stream, versions: [...string]
	_latest: [ if len(versions) > 0 {versions[0]}, ""][0]
	_deps: [ for d in s.depends_on {"`\(d)`"}]
	out: "| " + strings.Join([
		"`\(sid)`",
		apps[s.app].name,
		[ if _latest != "" {"`\(_latest)`"}, "_unreleased_"][0],
		[ if _latest != "" {"`\(sid)/v\(_latest)`"}, "—"][0],
		"`\(s.package)`",
		[ if len(_deps) > 0 {strings.Join(_deps, ", ")}, "—"][0],
		"`\(strings.Split(s.produced_by, "/")[1])`",
	], " | ") + " |"
}

#Table: {
	kind: string, heading: string, byStream: {...}
	_ids: list.Sort([ for sid, s in streams if s.kind == kind {sid}], list.Ascending)
	out: strings.Join(list.Concat([
		["#### \(heading)", "",
			"| Stream | Supports | Latest | Tag to pin | Daml package | Depends on | Produced by |",
			"| ------ | -------- | ------ | ---------- | ------------ | ---------- | ----------- |"],
		[ for sid in _ids {(#Row & {"sid": sid, s: streams[sid], versions: byStream[sid]}).out}],
		[""],
	]), "\n")
}

#Prose: out: strings.Join(list.Concat([
	["#### What each stream is", ""],
	list.Concat([ for sid in list.Sort([ for k, _ in streams {k}], list.Ascending) {
		let s = streams[sid]
		list.Concat([
			["**`\(sid)`** — \(s.summary)", ""],
			[ if s.notes != "" {strings.TrimSpace(s.notes)}],
			[ if s.notes != "" {""}],
		])
	}]),
]), "\n")

// The generated block, computed once so `generate` and `check` cannot disagree
// about what it should say.
#Block: {
	byStream: {...}
	out: strings.Join([
		_begin, "",
		(#Table & {kind: "app-model", heading: "Application models", "byStream": byStream}).out,
		(#Table & {kind: "library", heading: "Shared libraries", "byStream": byStream}).out,
		#Prose.out,
		"_Generated by `cue cmd generate`. Versions come from the Releases API; everything else from `dars.cue`._",
		"", _end,
	], "\n")
}

// ── The commands ────────────────────────────────────────────────────────────

command: generate: {
	fetch:  http.Get & {url: _api, request: header: "User-Agent": "public-dars-registry"}
	readme: file.Read & {filename: "README.md", contents: string}

	_block: (#Block & {byStream: (#ByStream & {parsed: (#Parsed & {raw: json.Unmarshal(fetch.response.body)}).out}).out}).out

	// A marker that does not match leaves `_head` holding the WHOLE file, so the
	// block is appended rather than replacing anything and the README silently
	// doubles. Not hypothetical — it happened when the README still said
	// `dars.toml`.
	_markersOK: len(strings.Split(readme.contents, _begin)) == 2 &&
		len(strings.Split(readme.contents, _end)) == 2

	guard: exec.Run & {cmd: ["sh", "-c", [ if _markersOK {"exit 0"},
		"echo '::error::README.md needs exactly one BEGIN/END marker pair to splice into' >&2; exit 1"][0]]}

	// Total, so a malformed README fails at `guard` with a sentence rather than
	// blowing up evaluation with "index out of range".
	_head: strings.Split(readme.contents, _begin)[0]
	_afterEnd: strings.SplitN(readme.contents, _end, 2)
	_tail: [ if len(_afterEnd) == 2 {_afterEnd[1]}, ""][0]

	write: file.Create & {$after: guard, filename: "README.md", contents: _head + _block + _tail}
	done:  cli.Print & {$after: write, text: "wrote README.md (\(len(streams)) streams)"}
}

command: check: {
	fetch:  http.Get & {url: _api, request: header: "User-Agent": "public-dars-registry"}
	readme: file.Read & {filename: "README.md", contents: string}

	_parsed: (#Parsed & {raw: json.Unmarshal(fetch.response.body)}).out
	_block:  (#Block & {byStream: (#ByStream & {parsed: _parsed}).out}).out

	// The failure this registry exists to prevent — and the one that put c7-lei
	// in an undocumented namespace.
	_undeclared: list.Sort([ for p in _parsed if streams[p.stream] == _|_ {p.tag}], list.Ascending)

	// A tag whose version is not three numeric components would sort as 0.
	_unparsable: [ for p in _parsed if !(#VNum & {v: p.version}).ok {p.tag}]

	// The committed block must match what `generate` would write.
	_current: strings.SplitN(strings.SplitN(readme.contents, _begin, 2)[1], _end, 2)[0]
	_wanted:  strings.SplitN(strings.SplitN(_block, _begin, 2)[1], _end, 2)[0]
	_stale:   _current != _wanted

	_errors: list.Concat([
		[ for t in _undeclared {"::error::`\(t)` is published but its stream is not declared in dars.cue"}],
		[ for t in _unparsable {"::error::`\(t)` has a version that is not <major>.<minor>.<patch>"}],
		[ if _stale {"::error::README.md's generated block is stale — run `cue cmd generate`"}],
	])

	_notices: [ for sid, _ in streams
		if len([ for p in _parsed if p.stream == sid {p}]) == 0 {
			"::notice::`\(sid)` is declared but has never been released"
		}]

	report: cli.Print & {text: strings.Join(list.Concat([
		_notices, _errors,
		[ if len(_errors) == 0 {"OK — map matches territory."}],
	]), "\n")}

	// After the report, so a CI failure names the stream instead of just failing.
	gate: exec.Run & {
		$after: report
		cmd: ["sh", "-c", "exit \([ if len(_errors) > 0 {"1"}, "0"][0])"]
	}
}

// `STREAM=c7lock DAR=path/to.dar cue cmd verify`
//
// A DAR states its own identity in META-INF/MANIFEST.MF, so nothing has to
// trust the filename. The package id matters because SCU resolves upgrades on
// (package name, version) while the ledger addresses packages by id, a content
// hash — two DARs can share a name and version and still be different bytes.
command: verify: {
	env: os.Getenv & {STREAM: string, DAR: string}

	manifest: exec.Run & {
		$after:  env
		cmd:     ["unzip", "-p", env.DAR, "META-INF/MANIFEST.MF"]
		stdout:  string
	}
	digest: exec.Run & {
		$after: env
		cmd:    ["shasum", "-a", "256", env.DAR]
		stdout: string
	}

	// JAR manifests wrap at 72 columns, continuing with a leading space.
	_lines: strings.Split(strings.Replace(manifest.stdout, "\n ", "", -1), "\n")
	_get: {k: string, out: [ for l in _lines if strings.HasPrefix(l, k+": ") {strings.TrimSpace(strings.TrimPrefix(l, k+": "))}, ""][0]}

	_nameVer: (_get & {k: "Name"}).out
	_sdk:     (_get & {k: "Sdk-Version"}).out
	_mainDalf: (_get & {k: "Main-Dalf"}).out

	// Package names contain dashes: the version is the last dash-delimited field
	// starting with a digit, not simply "after the first dash".
	_nv: regexp.FindSubmatch("^(.*)-([0-9][^-]*)$", _nameVer)
	_pkg: _nv[1]
	_ver: _nv[2]

	_idm: regexp.FindSubmatch("-([0-9a-f]{64})\\.dalf$", _mainDalf)
	_id:  _idm[1]

	_sha: strings.Split(strings.TrimSpace(digest.stdout), " ")[0]

	_want: streams[env.STREAM].package
	_ok:   _pkg == _want

    report: cli.Print & {text: strings.Join([
		"stream:          \(env.STREAM)",
		"package:         \(_pkg)",
		"version:         \(_ver)",
		"sdk_version:     \(_sdk)",
		"main_package_id: \(_id)",
		"sha256:          \(_sha)",
	], "\n")}

	gate: exec.Run & {
		$after: report
		cmd: ["sh", "-c", [ if _ok {"exit 0"},
			"echo '::error::\(env.DAR): package is `\(_pkg)`, expected `\(_want)`' >&2; exit 1"][0]]
	}
}

// `cue cmd selftest` — proves the validation actually fires.
//
// Covers only what review cannot see: whether schema.cue's referential rules
// actually RUN. `_appExists` and `appExists` read identically as intent while
// one silently does nothing, so one fixture per rule asserts vet REJECTS it.
// `good.cue` is the positive control — without it, a setup where everything
// errored would satisfy a suite that only looks for errors. See README.
command: selftest: {
	_bad: ["bad-app", "bad-dep"]

	control: exec.Run & {
		cmd: ["sh", "-c", "cue vet -c schema.cue testdata/good.cue"]
	}

	for name in _bad {
		(name): exec.Run & {
			$after: control
			// `!` inverts: the fixture MUST fail to vet.
			cmd: ["sh", "-c", """
				if cue vet -c schema.cue testdata/\(name).cue >/dev/null 2>&1; then
				  echo '::error::testdata/\(name).cue vetted clean — that check is not firing' >&2
				  exit 1
				fi
				"""]
		}
	}

	done: cli.Print & {
		$after: control
		text:   "selftest: 1 control + \(len(_bad)) referential rules proven to fire"
	}
}
